---
resources:
  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:making/concourse-version.git
      branch: master
      file: ver-demo/version
      private_key: {{private-key-github}}

jobs:
  - name: tag-master
    public: true
    serial: true
    plan:  
    - put: version
      params: {bump: patch}
